"""addes current_failed_checks field to endpoint target

Revision ID: 634f0634534d
Revises: 760cb6c3abc6
Create Date: 2026-07-24 18:07:48.126152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634f0634534d'
down_revision: Union[str, Sequence[str], None] = '760cb6c3abc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_target', sa.Column('current_failed_checks', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint_target', 'current_failed_checks')
    # ### end Alembic commands ###
