import httpx
from time import perf_counter


def complete_check(url, target_id, timeout):
    # This function should be called by another function (the scheduler).
    # It only returns enough data to build a CheckResult row, it does not persist
    # anything itself. Keeping HTTP-check logic separate from persistence logic
    # means this function can be tested with a mocked httpx call and no database
    # at all, and the caller decides how/when to call record_check_result.

    start_time = perf_counter()

    try:
        # timeout is passed in rather than hardcoded because different targets
        # can have different tolerances
        response = httpx.get(url=url, timeout=timeout)
        status_code = response.status_code

        # error_class stays None on success. This mirrors how the CheckResult
        # model already treats error_class as Optional: None means "nothing
        # went wrong at the request level," not "no data available."
        error_class = None

    except httpx.RequestError as e:
        error_class = type(e).__name__
        # status_code is None here because we never got an HTTP response at all,
        # there is no status code to report.
        status_code = None

    end_time = perf_counter()

    # perf_counter returns seconds as a float. CheckResult.latency_ms expects an
    # integer number of milliseconds, so we convert
    latency_ms = int(round((end_time - start_time) * 1000))

    # This dict's keys are deliberately a 1:1 match with CheckResult's columns,
    # excluding id (autogenerated) and checked_at (has a server_default), so the
    # caller can hand this straight to record_check_result without reshaping it.
    return {
        "target_id": target_id,
        "status_code": status_code,
        "latency_ms": latency_ms,
        "error_class": error_class,
    }

