services: # Sets services we want to use. i.e., our app and its dependencies. Each refers to a specific container
  app: # our application
    image: ghcr.io/nasrmoh/synthetic-uptime-monitor:${IMAGE_TAG:-production}
    container_name: app
    ports: #connects port 8000 on the host to port 8000 of the app container
      - "8000:8000"
    environment:
      # Compose creates an internal network and DNS entries for our services.
      # The hostname "db" resolves to the container's internal network IP,
      # NOT localhost, "localhost" inside this container means this
      # container itself. DATABASE_URL is expected to use "db" as the host,
      # e.g. postgresql://<user>:<password>@db:5432/<database-name>
      - DATABASE_URL=${DATABASE_URL} # url that app uses to connect to db
      - REDIS_URL=${REDIS_URL} # url that app uses to connect to redis
      - PYTHONUNBUFFERED=1 # Disable Python output buffering so logs appear immediately in `docker deploy logs`
      - SCHEDULER_ENABLED=True