services: # Sets services we want to use. i.e., our app and its dependencies. Each refers to a specific container
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/rules:/etc/prometheus/rules
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # prometheus datasource provisioning file
      - ./monitoring/grafana/provisioning/datasources/prometheus-datasources.yml:/etc/grafana/provisioning/datasources/prometheus-datasources.yml
      # dashboard configuration provisioning file
      - ./monitoring/grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      # exported dashboard json file
      - ./monitoring/grafana/dashboards/grafana-dashboard.json:/etc/grafana/dashboards/grafana-dashboard.json

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager-config.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager


volumes: # used for persistent data
  alertmanager_data:
  grafana_data: