server {
    listen 80;
    server_name synthetic.nasrmoha.dev;

    return 301 https://$host$request_uri;
}



server {
    listen 443 ssl;
    server_name synthetic.nasrmoha.dev;

    ssl_certificate /etc/letsencrypt/live/synthetic.nasrmoha.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/synthetic.nasrmoha.dev/privkey.pem;

    # Requests for exactly the root get redirected to docs
    location = / {
        return 302 /docs;
    }

    # All other requests are forwarded to FastAPI as before
    location / {
        proxy_pass http://127.0.0.1:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}